### ISSUE TITLE
Encrypted key

### ISSUE THREAD

**Issue by tomlis20** [BenExile/Dropbox#10]
Hi

I just set your Dropbox API and I noticed this line

$encrypter = new \Dropbox\OAuth\Storage\Encrypter('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');

What should I replace 'XXXX...' string with? Where can i find it?

**Comment by BenExile** [comment]
Hi @tomlis20 

The value passed to the Encrypter can be any 32 byte string you want. Obviously tokens will need to be decrypted with the same key they were encrypted, and how/where you store the key is up to you. Hope this helps.

**Comment by raweden** [comment]
if I've got it right, the Encrypter class is for encrypting tokens in the $_SESSION object?

**Comment by BenExile** [comment]
Hi @raweden 

That is correct, though it will be compatible with future storage handlers too.
