### ISSUE TITLE
Encrypted (or not) token for examples

### ISSUE THREAD

**Issue by ivomans** [BenExile/Dropbox#14]
The test/setup.php stores the token without using the Encrypter function. The examples/bootstrap.php is using the Encrypter function. Thus the examples don't work after running the setup.php.

Please make the setup.php and examples compatible. It would make things more obvious for a new user.

Regards,
Ivo Mans

**Comment by BenExile** [comment]
Hi @ivomans 

You do not need to run setup to run the examples provided. The test directory will contain unit tests once complete and the token file generated by the setup script is not designed to be compatible with the examples. If you're having problems running the examples then please explain the problem you're facing.

**Comment by ivomans** [comment]
Hi Ben,

Ok, so my problem could not be caused by what I thought. I checked now some futher what is happening:

When the App is not yet registered to the account the examples (I tested with accountinfo.php) give underneath error.
By using setup.php once this issue got solved, since here the process of registering an app is working fine.

Fatal error: Uncaught exception 'Dropbox\Exception' with message 'Access token is disabled. (Status Code: 401)' in /var/www/dev/test/Dropbox-Ben/Dropbox/OAuth/Consumer/Curl.php:103 Stack trace: #0 /var/www/dev/test/Dropbox-Ben/Dropbox/API.php(416): Dropbox\OAuth\Consumer\Curl->fetch('POST', 'https://api.dro...', 'account/info', Array) #1 /var/www/dev/test/Dropbox-Ben/Dropbox/API.php(76): Dropbox\API->fetch('POST', 'https://api.dro...', 'account/info') #2 /var/www/dev/test/Dropbox-Ben/examples/accountInfo.php(12): Dropbox\API->accountInfo() #3 {main} thrown in /var/www/dev/test/Dropbox-Ben/Dropbox/OAuth/Consumer/Curl.php on line 103

Furthermore I experience an extreme slow response when I enable the Encrypter function, although in the end it seems to work.

Regards, Ivo

**Comment by BenExile** [comment]
Hi @ivomans 

The above error suggests that the access token in your session has been disabled (app has been removed from your Dropbox account). I would suggest clearing your session and attempting to authenticate again.

I have not experienced any noticeable delay when using the Encrypter. Are you able to advise approximate delay time? Can you provide details of your environment so I can try and replicate the issue?

**Comment by ivomans** [comment]
Hi Ben,

I just timed a couple of page responses with encrypter varying between 90 and 200 seconds. Without the encrypter the response is almost immediate.
It's an Ubuntu 10.04 system, with Apache 2.2.14, PHP 5.3.2, cUrl 7.19.7, Mcrypt 2.5.8 (all regular Ubuntu packages). System load is less than 0.05, located in a decent data center, system is serving all kind of other PHP functions without a problem.

When I run same configuration on an Ubuntu 11.10 system (my laptop) the response is almost immediate.

I added some debug feedback to your encrypt function, and it turns out the time is consumed by the call "mcrypt_create_iv(16,0)".
Based on the comments on http://www.php.net/manual/en/function.mcrypt-create-iv.php I tried IV_SOURCE = MCRYPT_DEV_URANDOM, which seems to solve my issue.

I'm not an expert on Mcrypt, but this seems to be an improvement.

**Comment by BenExile** [comment]
Hi @ivomans 

I was able to replicate under Ubuntu Karmic and Lucid but not Windows or Ubuntu Natty. I will be looking into why this is, but using /dev/urandom should be fine for the purpose of generating an IV anyway. Please see commit b49576c and thank you for your contribution!
