### ISSUE TITLE
Check for headers not sent

### ISSUE THREAD

**Issue by ivomans** [BenExile/Dropbox#17]
Hi Ben,

I'm integrating your library in one of my webpage applications.
On some status page I do a check to see if the user has a connected Dropbox account.
To make this a bit smoother I would suggest you to add an extra condition to the authorise function in ConsumerAbstract.php:

Was: if (PHP_SAPI !== 'cli') {
Better: if ((PHP_SAPI !== 'cli') && (!headers_sent())) {

BTW: I've created a 'mysql.php' compatible to your 'session.php'. Code still needs some cleen up, but if you're interested I'm willing to make this code available.

Regards, Ivo

**Comment by BenExile** [comment]
Hi @ivomans,

Thank you. I will look into the `headers_sent()` check.

Please feel free to contact email me on ben@handcraftedbyben.co.uk to discuss integration of your code. I'm more than happy to consider contributions.

**Comment by BenExile** [comment]
Hi @ivomans 

I have decided not to include the `headers_sent()` check. I found it to be more useful to check at the time of instantiation so we can handle the error:

```
if(!headers_sent()){
    $storage = new \Dropbox\OAuth\Storage\Session();
    $OAuth = new \Dropbox\OAuth\Consumer\Curl($key, $secret, $storage, $callback);
    $dropbox = new \Dropbox\API($OAuth);
} else {
    // Can't redirect to authorisation page
}
```

Regards,
Ben
