### ISSUE TITLE
am using your api and getting these error

### ISSUE THREAD

**Issue by FARAZFRANK** [BenExile/Dropbox#18]
## putFile.php

/**
- Upload a file to the authenticated user's Dropbox
- @link https://www.dropbox.com/developers/reference/api#files-POST
- @link https://github.com/BenTheDesigner/Dropbox/blob/master/Dropbox/API.php#L80-110
  */

// Require the bootstrap
require_once('bootstrap.php');

// Create a temporary file and write some data to it
$tmp = tempnam('/tmp', 'dropbox');
$data = 'This file was uploaded using the Dropbox API!';
file_put_contents($tmp, $data);

// Upload the file with an alternative filename
$put = $dropbox->putFile($tmp, 'abc.txt');

print_r($put);

// Unlink the temporary file
unlink($tmp);

// Dump the output
var_dump($put);
## errors:

Uncaught exception 'Dropbox\Exception' with message 'App folder (sandbox) access attempt failed because this app is not configured to have an app folder. Should your access type be 'dropbox' instead? (Status Code: 403)' in C:\wamp\www\BenTheDesigner-Dropbox-b49576c\Dropbox\OAuth\Consumer\Curl.php on line 103

( ! ) Dropbox\Exception: App folder (sandbox) access attempt failed because this app is not configured to have an app folder. Should your access type be 'dropbox' instead? (Status Code: 403) in C:\wamp\www\BenTheDesigner-Dropbox-b49576c\Dropbox\OAuth\Consumer\Curl.php on line 103

and also , is it necessary to define $encryter key in bootstrap.php ??? 
$encrypter = new \Dropbox\OAuth\Storage\Encrypter('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');

**Comment by FARAZFRANK** [comment]
Thanks i have already solved this prob.

My app Access Type was 'Full Dropbox' and path was set according to "app folder" (a.k.a. sandbox). I have changed the path according my app access type "full Dropbox" (a.k.a. dropbox) at line 45 in API.php

public function __construct(OAuth\Consumer\ConsumerAbstract $OAuth, $root = 'sandbox')
{
$this->OAuth = $OAuth;
$this->setRoot($root);
}

CHANGED $root = 'dropbox'  (if your app access type 'Full Dropbox')

public function __construct(OAuth\Consumer\ConsumerAbstract $OAuth, $root = 'dropbox')
{
$this->OAuth = $OAuth;
$this->setRoot($root);
}

you can check your application access type here: https://www.dropbox.com/developers/apps

**Comment by BenExile** [comment]
Hi @FARAZFRANK777 

This behaviour is intended and you do not need to make modifications to the library directly. `sandbox` is the recommended Dropbox app access type and should you wish to override this, simply pass `dropbox` as the second argument when instantiating the Dropbox API or call the setRoot() method. Examples below:

```
$dropbox = new \Dropbox\API($OAuth, 'dropbox') // Setting the access type on instantiation
$dropbox->setRoot('dropbox'); // Setting the access type via setRoot()
```

It is not necessary to create an instance of the Encrypter object. This is an optional feature, however it's use is encouraged. OAuth tokens should be handled in the same sensitive manner as username/password combinations as they allow anyone who obtains them to act on behalf of a user.

**Comment by FARAZFRANK** [comment]
thanks for rapid reply,
i have done accordingly you.

i have one more question, how can i create a new directory(folder) in my dropbox account using this api library? i dint find anywhere. -Frank

**Comment by FARAZFRANK** [comment]
am done with this post: http://forums.dropbox.com/topic.php?id=58812
