### ISSUE TITLE
How save access token

### ISSUE THREAD

**Issue by onguyen** [BenExile/Dropbox#19]
Hello,

I am developing a PHP Script for content synching and it is running as a background process. But this Expiration of Access Token creates troubles for me, it requires a user interaction to click allow button for each new Web Session. Is there any method to avoid this user interaction and get a permanent Access Token for a Dropbox account. In my case i am using only one Dropbox account.

**Comment by italoveloso** [comment]
Hi,

I have the same doubt. I have an application where the folders and files need to be listed. The integration worked very well, but must avoid at all times the user's permission is required since it is used only one account. Is there any way around this? Thanks in advance.

**Comment by BenExile** [comment]
Hi

Please see the following link for advice on this. I am working on persistent storage handlers but they are not ready yet. https://github.com/BenTheDesigner/Dropbox/issues/16.
