### ISSUE TITLE
unserialize() error

### ISSUE THREAD

**Issue by kissgyorgy** [BenExile/Dropbox#20]
When I first try to authorize, then the the app come back to the callback URL and try to do for ex. $dropbox->accountInfo(); this message pops up:

A PHP Error was encountered
Severity: Notice
Message: unserialize() [function.unserialize]: Error at offset 0 of 192 bytes
Filename: Storage/Encrypter.php
Line Number: 69

What is it ? Where does it came from ? I googled after this and found:
http://davidwalsh.name/php-serialize-unserialize-issues
but it doesn't solve the issue applied to Encrypter class encrypt and decrypt functions.
However I get the account info but dont understand why it works, because every other operation works well after the forst authorization.  Do you have any idea ?
I use Codeigniter by the way.

**Comment by BenExile** [comment]
Hi @Walkman 

I have only encountered this problem when the encryption key is changed after a token has been obtained. As the decryption will fail, so will unserializing the token.

Please confirm that the encryption key was not changed between requests and I will investigate further. Commit 91c6e5a checks for failed unserialisation and throws an Exception which will allow you to handle this error more gracefully.

**Comment by kissgyorgy** [comment]
Yes, I cahnged it manually to test it. So it will never come up when I request token from a new user ?

**Comment by kissgyorgy** [comment]
Thanks for the change ! Anyway, your code is very clean and easily usable ! ;-)

**Comment by BenExile** [comment]
Hi @Walkman 

This issue will still occur if you encrypt tokens with one key and try to decrypt using another. This means that any change to your encryption key will mean that tokens issued before that change will no longer work. I will look into ways we can handle this, but for now please bear this in mind.

Thank you for the compliments!

Regards,
Ben

**Comment by kissgyorgy** [comment]
I did not looked into details yet, does it mean you use only one key for every user? I tought the way to use your scripts that I generate every user a unique key and assign to them, and when the user log in I use that key. Am I right ?

**Comment by BenExile** [comment]
Hi @Walkman 

It's your decision whether you use a unique encryption key per user or use a shared key. In both scenarios the above applies - you must decrypt with the same key that you encrypted the token with. If at any point a unique/shared key is changed, any tokens encrypted using that key will be useless as you will be unable to decrypt them.

**Comment by kissgyorgy** [comment]
ok, got it thanks !!

**Comment by BenExile** [comment]
Hi @Walkman 

No problem, glad I could help :)
