### ISSUE TITLE
Upload file within a folder

### ISSUE THREAD

**Issue by earth** [BenExile/Dropbox#21]
Hello,

In my drop box folder i have a folder named 'Public'. How can i upload a file within 'Public' folder using the API.

**Comment by BenExile** [comment]
Hi @earth 

Your application will need to have full Dropbox access. You'll then be able to putFile/putStream into that directory.

**Comment by earth** [comment]
Hello,

I have full Dropbox access.

I am using the following code to upload file to upload a file within 'Public' folder. The file is getting uploaded to the root folder and not within 'Public' folder.

$put = $dropbox->putFile($tmp, '/Public/api_upload_file.txt');

**Comment by BenExile** [comment]
Hi @earth 

Sorry for the late reply - I'm looking into this and will update when I have an answer. In theory that code should work, though.

**Comment by earth** [comment]
Thanks

**Comment by cahva** [comment]
putFile method's third parameter is the path. So this works:

```
$put = $dropbox->putFile($tmp, 'api_upload_file.txt','Public');
```

**Comment by earth** [comment]
Thanks.

On Wed, Jun 6, 2012 at 4:12 AM, Markku Virtanen <
reply@reply.github.com

> wrote:
> 
> putFile method's third parameter is the path. So this works:
> 
>    $put = $dropbox->putFile($tmp, 'api_upload_file.txt','Public');
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/BenTheDesigner/Dropbox/issues/21#issuecomment-6138832

## 

Best Regards,
Rupak
Project Manager, Earth Technology Pvt. Ltd.
www.earthtechnology.co.in

**Comment by BenExile** [comment]
Thanks @cahva - I forgot this changed a while back, separating file name and path (using the original file name if an alternative is not provided).
