### ISSUE TITLE
Dropbox - Console

### ISSUE THREAD

**Issue by rokai3009** [BenExile/Dropbox#22]
Hello everyone,

I run dropbox code by browser, it works, but when I run dropbox code by console, it doesn't work and no error
Thanks for any suggest, I'm just begginer :(

Best wishes

**Comment by BenExile** [comment]
Hi,

Can you provide more information? What code are you trying to run via the CLI?

**Comment by rokai3009** [comment]
Hi,
I want upload a file, I use test.php :
                $protocol = (!empty($_SERVER['HTTPS'])) ? 'https' : 'http';
        $callback = $protocol . '://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];

```
    // Instantiate the required Dropbox objects
    $encrypter = new \Dropbox\OAuth\Storage\Encrypter('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');

    $storage = new \Dropbox\OAuth\Storage\Session($encrypter);

    $OAuth = new \Dropbox\OAuth\Consumer\Curl($key, $secret, $storage, $callback);
    $dropbox = new \Dropbox\API($OAuth,'dropbox');
            $tmp = tempnam('/tmp', 'dropbox');
    $data = $filename;

    // Upload the file with an alternative filename
    $put = $dropbox->putFile($tmp, $file_name_upload);
```

I use localhost to run test, when run by browser it works, but I use one file .bat with content :
             C:\xampp\php\php.exe -f c:\xampp\htdocs\test_dropbox.php
it's don't work and no error :(

**Comment by BenExile** [comment]
Hi @rokai3009 

This library was never intended to be run via the CLI, in fact [bootstrap.php](https://github.com/BenTheDesigner/Dropbox/blob/master/examples/bootstrap.php#L8-11) prevents this. The OAuth specification states that the user must be redirected to the service provider to authorise the request which we cannot achieve on the command line. The code above won't work and I will not be looking at this in the future.
