### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by Raketten** [BenExile/Dropbox#27]
Hi Ben,

Is it possible to supply credentials so that user does not have to admit the app each time he upload a new file? I am thinking on moving the upload to a queue as it take so long, and then user cannot hit any buttons for me...

Henrik

**Comment by BenExile** [comment]
Hi @Raketten 

Users should not need to authorise the app for each uploaded file, just once per session (assuming you're using the default session storage handler I have provided). You can implement your own persistent storage handler if this is what you require, but this is not something I can implement without further planning.

**Comment by Raketten** [comment]
Hi Ben,

Thanks for your reply. I eventually went with curl and saved the tokens in my database. 

Thanks anyway,

Henrik
