### ISSUE TITLE
Encryption error

### ISSUE THREAD

**Issue by twistedpixel** [BenExile/Dropbox#28]
Hey, this looks fantastic but I'm having a little bit of trouble getting started. I'm getting a warning about open_basedir and certain curl functions (I know this is my Plesk server being stupid, even though I disabled open_basedir in both php.ini AND Apache httpd.conf, it is still in effect and I want to strangle it) but the second issue is an error:

Fatal error: Uncaught exception 'Dropbox\Exception' with message 'OAuthError in API v1+. Request mis-signed: Invalid or Missing Signature (Status Code: 401)'

Is this to do with curl/open_basedir do you think and not something I've done wrong in the bootstrap?

I replaced the XXXX with my public/private keys but I'm confused as to what the third placeholder XXXXXX is all about? The Encryptor one.

I'd really like to get started using this but I'm struggling so any help you can offer would be great.

Thanks!

Scott

**Comment by BenExile** [comment]
Hi Scott,

#### cURL & open_basedir

There are known issues with cURL and open_basedir. Please see [here](https://github.com/BenTheDesigner/Dropbox/issues/23) for a similar issue which has been resolved.

#### Encrypter

The Encrypter provides an optional, but recommended feature. The OAuth tokens obtained will be encrypted to AES-256 standard to prevent them being used in replay attacks. OAuth tokens allow an application to interact with a thid-party service on behalf of the user - they should therefore be handled in the same sensitive manner as a username/password combination.

The value passed to the Excrypter object (`$encrypter` in the bootstrap) is the encryption key - a secret value that specifies how the plaintext value should be converted to cipher. By default this library uses 32-byte keys and encrypts to AES standard (256-bit).

**Comment by twistedpixel** [comment]
Awesome, Thanks Ben.

I'll have a look into these!
