### ISSUE TITLE
Writing file from file upload form.

### ISSUE THREAD

**Issue by hypeunion** [BenExile/Dropbox#32]
Hi Ben, thanks for supplying the code!

I'm having trouble writing a file to my Dropbox account using an upload input in a form. The file is being uploaded properly, and a file named "test.jpg" is being created in Dropbox, but the file created on Dropbox is broken and without contents. My code is below...is there something I've done wrong?

```
    function handle_uploaded_file()   {

$protocol = (!empty($_SERVER['HTTPS'])) ? 'https' : 'http';
$callback = $protocol . '://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];

spl_autoload_register(function($class){
    $class = str_replace('\\', '/', $class);
    $var = include_once(TEMPLATEPATH . '/api/Dropbox/' . $class . '.php');
});

$encrypter = new \Dropbox\OAuth\Storage\Encrypter('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');
$storage = new \Dropbox\OAuth\Storage\Session($encrypter);
$OAuth = new \Dropbox\OAuth\Consumer\Curl(DROPBOX_KEY, DROPBOX_SECRET, $storage, $callback);
$dropbox = new \Dropbox\API($OAuth,'dropbox');


$tmp = tempnam('/tmp', 'dropbox');

fwrite($tmp, $_FILES["uploaded_file"]["tmp_name"]);

$put = $dropbox->putFile($tmp,"test.jpg");

fclose($tmp); // this removes the file

    }
```

**Comment by BenExile** [comment]
Hi @hypeunion 

You are not using fwrite correctly. The [documentation](http://php.net/manual/en/function.fwrite.php) explains that the second argument is the data to be written to the file. In your example you are simply writing the temporary filename as the file data which is what is causing the JPEG to be corrupt.

If you have a requirement to create an intermediate file look at [move_uploaded_file](http://uk.php.net/manual/en/function.move-uploaded-file.php) instead. You could also consider uploading the file to Dropbox direct from it's temporary uploaded location:

`$put = $dropbox->putFile($_FILES["uploaded_file"]["tmp_name"], 'test.jpg');`

Hope this helps!

**Comment by hypeunion** [comment]
Thanks for the help Ben!

**Comment by BenExile** [comment]
No problem! Closing this issue as resolved.
