### ISSUE TITLE
why first visite dropbox API should need to link to dropbox?

### ISSUE THREAD

**Issue by ouewqa** [BenExile/Dropbox#33]
I have used another dropbox php api, that php api first visit also need to link dropbox, but it can save response in a file,then don't need to link to dropbox any more, Whether or not i delete the cookie or change a browser.

Does this api has the same function?

**Comment by BenExile** [comment]
Hi,

At present the library does not provide persistent storage. You can add this yourself, though, as a few others have.

This is being addressed by introducing a storage handler built on PDO. Please see recent commits.

**Comment by BenExile** [comment]
Closed due to inactivity
