### ISSUE TITLE
How to create folder?

### ISSUE THREAD

**Issue by bikeshm** [BenExile/Dropbox#34]
hai,
     How can i create a folder in drop box home directry

$dropbox->createFolder() not working

code:-

$dropbox->createFolder('new_folder','dropbox');

o/p:-

Fatal error: Call to undefined method Dropbox\API::createFolder() in /home/xxxxxxx/public_html/test/Dropbox/examples/sample.php on line 42

plz help.....

**Comment by BenExile** [comment]
Hi,

The error is as described - createFolder() is undefined. The correct method is create($path), where $path is the path to the folder you wish to create, relative to your root (sandbox or dropbox). Hope this helps.

**Comment by bikeshm** [comment]
Hi Ben,

  It is working, thank you sooooooooo much, 

and thanks for replying 

my code:-

$create_new_folder = $dropbox->create('new_folder','dropbox');

print_r($create_new_folder);

Regards,
Bikesh

**Comment by BenExile** [comment]
Hi Bikesh,

You're welcome.

Note that you don't need to pass the second argument, it won't do anything. You set your root when instantiating the \Dropbox\API object and it is set for subsequent calls.

**Comment by bikeshm** [comment]
ok 

thanks allot
