### ISSUE TITLE
Trouble Getting Started

### ISSUE THREAD

**Issue by gowings0** [BenExile/Dropbox#35]

**Comment by BenExile** [comment]
This library is intended for use in web apps, so in your browser. You could make modifications to allow execution from the command line, but it won't be seamless as the OAuth flow cannot be completed via CLI alone.

What are you aiming to build?

**Comment by BenExile** [comment]
Hi,

I am closing this issue as its not related to the library itself. If you have any SDK specific issues please do raise them.

There are plenty of resources that explain how to install and configure a LAMP/WAMP/LEMP stack out there something that I'm not going to explain here.

**Comment by BenExile** [comment]
Once you have your stack installed you'll be able to run the examples and begin to build your application. Good luck!
