### ISSUE TITLE
GetAccessToken

### ISSUE THREAD

**Issue by Timpet123** [BenExile/Dropbox#36]
When trying to use the function i get this error: 
Fatal error: Uncaught exception 'Dropbox\Exception' with message 'Request token not found. (Status Code: 401)'

**Comment by BenExile** [comment]
Hi,

The visibility of getAccessToken() is only public for the purpose of being accessible to the unit test setup script. You should not need to call this method directly.

What are you trying to achieve?

**Comment by Timpet123** [comment]
Im trying to make a backup script that can run from a cron job where the user does not need to suply the account credits everytime, but just once doing a setup of the script where I understod i should save and use the access token for further use.

Sorry for the bad english

**Comment by BenExile** [comment]
Hi @Timpet123 

This issue has been raised before. Please see https://github.com/BenTheDesigner/Dropbox/issues/16 for my proposed solution, assuming you aren't going to use the new persistent handler, which stores tokens in a database.

Please advise if you're still having issues.

**Comment by Timpet123** [comment]
Since i dont have commandline access i cant run the setup file, i do want to store the tokens in my DB. Perhaps you could create and example on how to do this not useing the commandline?

**Comment by BenExile** [comment]
Hi,

You don't have to acquire the token on your server, it could be done on your local machine and the resulting oauth.token uploaded afterwards. I'd encourage you to use this method for single user applications as it will reduce the associated overheads.

The examples do describe how to use the persistent storage handler. If it is not clear enough I will try my best to explain.

----- Reply message -----

**Comment by Timpet123** [comment]
It would be great if you could explain how i could get the access token, store it in my DB (I can do this my self), and then use it further on, but not the commandline way. :)

**Comment by BenExile** [comment]
The PDO storage handler will provide this functionality. I need to provide the DB table schema, but its not too complex. You could, in fact, check the source for the fields required.

The example usage in bootstrap.php shows how to use a hard coded user ID, which is what you'll want to do to achieve single user access.

**Comment by BenExile** [comment]
Resolved

**Comment by Timpet123** [comment]
Fast replys and good service!
