### ISSUE TITLE
How can I test if user is connected to dropbox or not ?

### ISSUE THREAD

**Issue by bijufun** [BenExile/Dropbox#37]
is there any standard / inbuilt function to check if user is connected to dropbox or not?

I am implementing your code in one of my wordpress project. I want to sync with dropbox via ajax function if its connected else redirect to dropbox for acess token.

**Comment by BenExile** [comment]
The library detects whether an OAuth access token has been acquired for the user (either stored in their session or DB). You don't need to detect manually. Please see the examples provided which will automatically redirect you to Dropbox if a token is not available.

**Comment by bijufun** [comment]
Ya , I agree..

But i need some function like 

checkIfLoginInDropbox()

and it returns true / false to me.

I need to make this test and make some decision base on it.

PS : where can i get resource for storing token access in database. I am confused how can i relate my wordpress users with drobox users. Do i need to change the table oauth_tokens?
And is oath_token and user id enough to syn with dropbox directly without logging and approving my apps coz'  dropbox only returns me one token. I used to get 2 tokens - oath and secret when i apply dropbox in my dot net project.

**Comment by BenExile** [comment]
Hi,

After creating your storage object, you can check if an access token has been obtained for a user by calling get():

```
$userID = 1; // The unique user ID for your WordPress user
$storage = new \Dropbox\OAuth\Storage\PDO($encrypter, $userID);
$storage->connect('localhost', 'db', 'user', 'pass');

if ($storage->get('access_token')) {
    // User has an OAuth access token
} else {
    // User does not have an OAuth access token
}
```

You do not need to manually associate WordPress users with Dropbox users, the library does this by using the unique ID assigned to your users in your own users table as the userID value in the oauth_tokens table.

Hope this helps.

**Comment by bijufun** [comment]
Will try this..

Really impressed with your prompt reply..
Amazing & Instant support !!!

**Comment by cyruskafaiwu** [comment]
Sorry for the bump. But, the code that you posted will be able to detect if the user has authorized the connection between the program and Dropbox.

And what happens if the user, deletes the application from his dropbox account.
