### ISSUE TITLE
PDO Storage isn't working (for me at least)

### ISSUE THREAD

**Issue by jacklightbody** [BenExile/Dropbox#38]
I am working on a script that uses access tokens.
my current code is this

```
$encrypter = new \Dropbox\OAuth\Storage\Encrypter('60173754138144501737729dfd041f1i');//this is just a random key, not the one i'm actually using.
$userID = 1; // using a constant one for testing
$storage = new \Dropbox\OAuth\Storage\PDO($encrypter, $userID);
$storage->connect('localhost', 'dbname', 'user', 'pass');

$OAuth = new \Dropbox\OAuth\Consumer\Curl($key, $secret, $storage, $callback);
$dropbox = new \Dropbox\API($OAuth);
-------table structure------
dbname
    oauth_tokens
        userID
        token
```

however, nothing actually gets inserted into the table. Do I need to call the set method of the PDO helper, or is it something else. Thanks!

**Comment by BenExile** [comment]
Hi,

Can you advise whether you have error reporting turned on and whether you receive any errors at all? If there was a problem inserting/selecting then PDO would throw an Exception.

FYI, If you already have a token stored in your session the library will use that and not attempt to acquire a new one or retrieve an existing one from the database. Please clear your browser cache and run the application, replying with your results.

**Comment by jacklightbody** [comment]
Error reporting is set to e_all
Database is empty, so that shouldn't be a problem. What happens is I get stuck in a loop, go to page-> authorize-> go back to page (some get variables are present) hen when I try to go to a new page, the process restarts.

**Comment by BenExile** [comment]
I'm going to need to see more code. I can't replicate the loop at my end once the token has been obtained.

**Comment by jacklightbody** [comment]
Hi,
What code do you want? I haven't changed bootstrap.php from other than the storage part and filling in the secret/public keys. I can try to get a demo up too, if that would help.

**Comment by jacklightbody** [comment]
Never mind, sorry to waste your time. I was routing to a 404 and stopping execution before the boostrap file was being loaded.
