### ISSUE TITLE
Uncaught exception 'Dropbox\Exception' with message 'Expecting a 32 byte key, got 15'

### ISSUE THREAD

**Issue by Donaldini** [BenExile/Dropbox#39]
When trying to run examples/accountInfo.php I get the following error:

Fatal error: Uncaught exception 'Dropbox\Exception' with message 'Expecting a 32 byte key, got 15' in /Applications/MAMP/htdocs/testing/Dropbox/Dropbox/OAuth/Storage/Encrypter.php:39 Stack trace: #0 /Applications/MAMP/htdocs/testing/Dropbox/examples/bootstrap.php(38): Dropbox\OAuth\Storage\Encrypter->__construct('f5zbh1wef86ro3l') #1 /Applications/MAMP/htdocs/testing/Dropbox/examples/accountInfo.php(10): require_once('/Applications/M...') #2 {main} thrown in /Applications/MAMP/htdocs/testing/Dropbox/Dropbox/OAuth/Storage/Encrypter.php on line 39

I set the following in the bootstrap.php file:
$key, $secret and $encrypter = new \Dropbox\OAuth\Storage\Encrypter($key);

**Comment by BenExile** [comment]
Hi,

The key passed to the encrypter is not your consumer key, but a secret encryption key used to secure stored OAuth tokens.

That Exception simply means the key is not long enough. Using the default settings you must provide a 32 byte key - your key is only 15 bytes.

**Comment by Donaldini** [comment]
Should I then not use this information:
http://i.imgur.com/RF1rn.png

**Comment by BenExile** [comment]
You need to pass your app key and secret to the OAuth consumer on instantiation as per the example I provided (bootstrap.php). You also need to generate a separate encryption key to pass to the encrypter.
