### ISSUE TITLE
How do I get the absolute url?

### ISSUE THREAD

**Issue by simwatts2** [BenExile/Dropbox#41]
Racking my brains here, and probably straight forward. but how do I get the full url to use with dropbox. Say i have an image - how would I get to display the image, or file. I can get a json response list but it will only show the name. ie /koala.jpg.

Say I am on localhost/dropbox/getfile.php - , and have an image in the root in sandbox mode. do I append something to the end. Or am I on the wrong direction here.

ie localhost/dropbox/getfile.php?file=koala.jpg.

I really need to get this quite urgent, but I think I am missing something really simple here.

**Comment by BenExile** [comment]
Please see the examples provided. This is demonstrated in getFile.php.

**Comment by simwatts2** [comment]
Hi Ben. Thanks for your work on this project.

The Abolute path to was not given in this. I found a solution by using media.
ie $dropbox->media($path);

This gives a complete link, that expires in 4 hours.

Getfile only gives the name of the file in the link, ie koala.jpg, of foo.txt.

ie with get file  -/koala.jpg

with media - https://dl.dropbox.com/0/view/3vp7wu77ikiafe4/Apps/appname/koala.jpg

Does this make sense.

Simon

**Comment by BenExile** [comment]
Hi Simon,

Sorry, I misunderstood what you were asking. Correct, the media/ call will allow you to link directly to that file.
