### ISSUE TITLE
Needs a way to delete the session and reconnect the session again

### ISSUE THREAD

**Issue by alexdemers** [BenExile/Dropbox#44]
Hi Ben,

Excellent library. Our product is almost done except one bug (or something I don't understand with OAuth tokens. I need a way for the user to delete the connection with Dropbox via our third-party service. I figured I just delete the row in oauth_tokens table that you provided. Afterwards when trying to connect again, I get "Token is not an authorized request token. (Status Code: 403)" even if the token doesn't exist in the table.

I looked at all the issues on github and throughout the library for a way to delete the user tokens.

Is that something you will implement soon? Or is it something I don't understand with the way OAuth tokens work?

Thanks, and again, great work! 

Edit: I should mention that if I change the Encryption key, everything works again. But I think this invalidates every oauth_tokens.

Edit 2: Ok, I figured out why I got this error. The $_SESSION variable was still using the old access token. Now it needs a way to delete that if we get a 403 error.

**Comment by BenExile** [comment]
Hi @alexdemers 

I've addressed this issue in commit 19852f8. Please pull the changes and advise whether your problem persists.

**Comment by alexdemers** [comment]
As I am not familiar with git/Github, I applied the changes manually in the code and it did worked. This also fixed the issue where one would see the Dropbox page to login, but instead leaves the page and goes back to the application. Because the request_token was there but not the access_token, the library would think that it had a correct access_token. It assumed that the user was entering his Dropbox credentials without leaving that page.

Now, after playing a bit with the implementation of this library, I figured that the easy way to delete the access to Dropbox it would be:

``` php
<?php
unset($_SESSION['dropbox_api']);
$db->query("DELETE FROM oauth_tokens WHERE userID = $user_id");
```

Am I missing something else to have the full cycle of Connecting to Dropbox -> Disconnecting from Dropbox -> Reconnecting to Dropbox?

**Comment by BenExile** [comment]
Hi,

I've added methods to each of the storage handlers to delete tokens from the session and filesystem/database (see commit eb260c7). You can simply call `$storage->delete()` to make use of this feature.

To give the user peace of mind that your application can no longer interact with Dropbox on their behalf, you can instruct them to visit https://www.dropbox.com/account#applications and revoke access to the application.

Hope this helps :)

**Comment by alexdemers** [comment]
That's awesome Ben! I'll implement this in my application :D

**Comment by BenExile** [comment]
Thanks, Alex. This issue is now closed.
