### ISSUE TITLE
Skip User Authorization?

### ISSUE THREAD

**Issue by hipwebdesign** [BenExile/Dropbox#46]
I'd like to output a list of download links to files in one of my folders. 

These links should be downloadable regardless of whether the visitor has a Dropbox account or not.

I can't seem to output my content without first obtaining an authorization token for a Dropbox user.

Is this possible?

**Comment by BenExile** [comment]
Hi,

The easiest way to do this would be to use the FIlesystem storage handler and a fixed user ID (code provided in examples). Once you obtain an access token for the user ID, it can be used for subsequent requests without requiring the user to authorise your app.

**Comment by hipwebdesign** [comment]
Thanks for such a quick answer -- and a great SDK!

**Comment by BenExile** [comment]
No problem, glad I could help :)
