### ISSUE TITLE
Simultaneouse upload

### ISSUE THREAD

**Issue by kspam** [BenExile/Dropbox#48]
I've found that if I put a file to 2 (or more) users in the same time. One will upload and another will queue. Second one will upload until previous one complete. Is it possible to upload simultaneously?

**Comment by BenExile** [comment]
This library provides no way to upload files to multiple Dropbox accounts at once. I won't be implementing this any time soon, if at all.

If you are uploading the same file, I'd consider looking at the copyRef call, which will copy files from one Dropbox to another, reducing execution times and bandwidth overheads dramatically.

**Comment by BenExile** [comment]
Closed due to inactivity
