### ISSUE TITLE
Access all folders

### ISSUE THREAD

**Issue by ratok** [BenExile/Dropbox#49]
Hi,
I'm trying to upload a file into a specific folder in my dropbox root, using:
$put = $dropbox->putFile($tmp, 'api_upload_test.txt', 'MyFolder');

I get always the error message: 'App folder (sandbox) access attempt failed because this app is not configured to have an app folder. Should your access type be 'dropbox' instead? (Status Code: 403)'.

The app was created with the setting Access type Full Dropbox.

How do I switch the access type in my app? I don't find any option for that in the bootstrap.php

Thanks, any support is appreciated.

**Comment by BenExile** [comment]
Hi,

You can either pass 'dropbox' as the second argument when instantiating the \Dropbox\API object, or call $dropbox->setRoot('dropbox') after instantiation. Hope this helps.

**Comment by ratok** [comment]
Great, thanks a lot. Perfect.

**Comment by BenExile** [comment]
You're welcome
