### ISSUE TITLE
Timezone Problem

### ISSUE THREAD

**Issue by ghost** [BenExile/Dropbox#51]
First, thank you for this. The code works great.

Now, my problem: In an array created by $dropbox-metaData all my files have the right time displayed but are in the wrong timezone. The timezone is set to Europe/Berlin.

Do you know how to change the timezone?

Thanks in advance.

**Comment by BenExile** [comment]
Hi,

Please provide more detail, the response received from the API along with what is wrong and what you'd expect the correct result to be.

**Comment by ghost** [comment]
Hi, sorry about that.

I am loading every file in an App folder to an array using the $dropbox-metaData. When I check the "modified" value or the "client_mtime" of a file the times are listed in the wrong timezone (Europe/Berlin). I checked my account settings on Dropbox and my account is set to the correct timezone (New York). 

I would like to have the times listed in the correct timezone (New York).

Thanks for the quick response.

**Comment by BenExile** [comment]
No problem. All times should be returned as GMT as detailed by the API documentation. If you require these in your local time you'll need to format them yourself. Something similar to the code below should help you:

```
// Get the metadata for the file/folder specified in $path
$metaData = $dropbox->metaData($path);

date_default_timezone_set('America/New_York');
$date = date('D, d M Y H:i:s O', strtotime($metaData['body']->modified));

// Dump the output
var_dump($date);

```

**Comment by ghost** [comment]
Whoops, I must have overlooked that. That makes perfect sense. 

Keep up the great work!

**Comment by BenExile** [comment]
Thanks :)
