### ISSUE TITLE
Uplaod uin  my account

### ISSUE THREAD

**Issue by anletbel** [BenExile/Dropbox#52]
I want to upload from a web form, files to my Dropbox folder.

My problem is I always ask q are logged into does not use my account information to log.

And would require that anyone from anywhere up my account info.

How I can fix this?

**Comment by BenExile** [comment]
Apologies for the late reply. I don't understand your problem so if you're still having this issue, please comment again as clearly as possible.

**Comment by BenExile** [comment]
Closed due to inactivity
