### ISSUE TITLE
OAuth Access Grant

### ISSUE THREAD

**Issue by miroslavw** [BenExile/Dropbox#53]
Hello please pardon my ignorance but I would like to use a single shared dropbox account in a business application that only requires access to be granted once and will be accessible across browsers and without expiration. Is this possible? It seems as though I can authenticate/grant access once in Chrome browser and functionality works fine but switching over to Firefox for testing requires that I re-authenticate. Is it possible to create the handshake once and not require it further unless I revoke in my Dropbox account?

Thank you in advance, Miro

**Comment by BenExile** [comment]
Hi Miro,

It sounds as though you're attempting to achieve persistent storage using the session storage handler. This is not possible, and you will need to re-authenticate for each session. You can use the PDO or Filesystem storage handlers to achieve what you describe - an example of usage can be found in examples/bootstrap.php. Hope this helps.

**Comment by miroslavw** [comment]
Ah thank you Ben I had an old copy of the files - will update now.
