### ISSUE TITLE
Catchable fatal error: Object of class stdClass could not be converted to string in /Applications/XAMPP/xamppfiles/htdocs/dropbox/Dropbox-master/Dropbox/OAuth/Consumer/Curl.php on line 103

### ISSUE THREAD

**Issue by samatrouh** [BenExile/Dropbox#55]
Hi,
In the examples, when I try to upload a small file to the server but get the following error  `Catchable fatal error: Object of class stdClass could not be converted to string in /Applications/XAMPP/xamppfiles/htdocs/dropbox/Dropbox-master/Dropbox/OAuth/Consumer/Curl.php on line 103`. Please let me know what details you need to grab of my system.

Any help is greatly appreciated.
Cheers,
Sam

**Comment by BenExile** [comment]
Hi Sam,

Sorry for the delayed reply - been stacked. Are you still having this issue? If so please provide as much information as possible about the request that was sent that resulted in this error. I've not come across it and have, as you can imagine, been uploading/downloading files of all sizes and types.

Thanks

**Comment by BenExile** [comment]
Closed due to inactivity
