### ISSUE TITLE
Let getAuthoriseUrl return a plaintext url

### ISSUE THREAD

**Issue by freemann** [BenExile/Dropbox#56]
Why does getAuthoriseUrl(), in the test download,  returns a plaintext url and redirect me in a browser?
I need the url, but i can't figure out why it redirects me in stead of returning a plaintext url.

Who can explain to me, how i can get this work?

**Comment by BenExile** [comment]
Hi @freemann, 

At present, the constructor for the cURL consumer automatically calls the authenticate() method of the parent class, which redirects you if you're not authenticated. I may patch this so auto-redirecting is optional, but will default to true to provide backwards compatibility for those already using the library.

It makes sense that you can choose what to do if a user isn't authenticated. Expect an update by the end of the week. 

Hope this helps.

**Comment by freemann** [comment]
Hi @BenTheDesigner,

thanx for the very quick and positive response on my question/problem.

Hope to se the patch soon and i want to thank you in advance for you're time and work!

Regards,
Marco (Freemann)

**Comment by freemann** [comment]
Hi @BenTheDesigner,

I don't want to pressure you, what do you mean with "Expect an update by the end of the week"?
At the moment i'm "waiting" on the fixes (see my other issue, everything goes through authentication and redirects to Dropbox).

Thanks and best regards,
Marco

**Comment by jmcbee** [comment]
I'm not sure why this is closed, it still redirects.
