### ISSUE TITLE
Bootstrap as a class

### ISSUE THREAD

**Issue by enkay** [BenExile/Dropbox#58]
Is there a way to wrap this bootstrap into a class as to not have variables interfering with the rest of the code? I'm trying to do that but keep running into road blocks.

Suggestion: The integrated storage makes it a lot harder to modify the code. Storing tokens in a users database could be left to developers as a way to streamline this API.

Maybe something like this would be easier to integrate into applications.

$dropbox_client = new Dropbox_Client($token);
$dropbox = new  Dropbox_API($dropbox_client);

Thanks for your work.

**Comment by BenExile** [comment]
Hi @enkay 

The sole purpose of the bootstrap is for inclusion by the examples provided. You should not be including it in your application as-is. You need to take the parts from the bootstrap that are relevant to you, and put just those into your application - that way you don't have unnecessary variables defined. What 'road blocks' have you come across?

If you could elaborate on why the storage mechanisms make it difficult to modify the code (also which code you mean, and what you're trying to do) that would make it much easier to understand your problem. At the moment I don't see any issue - this library is used in production on many sites and hasn't caused any development issues.

**Comment by BenExile** [comment]
Closed due to inactivity
