### ISSUE TITLE
Just wondering if I can access files in the dropbox folder using your sdk

### ISSUE THREAD

**Issue by Nick5679** [BenExile/Dropbox#6]
Hi,

Thanks for the sdk. I was planning to use it in my project. I did see your examples. It shows how to upload file and see account info. Is there any method to retrieve folder names and filenames. And also download it to my server using the php sdk when requested. Is this possible using your sdk. 

I appreciate all your help.

Thanks.

**Comment by BenExile** [comment]
Hi @Nick5679 

The library provides access to all V1 API methods available to date, though I am still working on examples and associated documentation. Please see the [metaData](https://github.com/BenTheDesigner/Dropbox/blob/master/Dropbox/API.php#L121-143) and [getFile](https://github.com/BenTheDesigner/Dropbox/blob/master/Dropbox/API.php#L100-119) methods which should provide the functionality you require. You may also want to check out the Dropbox [API reference](https://github.com/BenTheDesigner/Dropbox/blob/master/Dropbox/API.php#L121-143) for their official documentation.

**Comment by Nick5679** [comment]
I appreciate all your help.

Thanks.
