### ISSUE TITLE
Utilize Dropbox as only one user. 

### ISSUE THREAD

**Issue by chrisamoore** [BenExile/Dropbox#60]
Hi Ben, 

What would you recommend for using the API, as only our Company to manage all of the files in a single directory or subset of directories, Preferably using the shares method to grant access when needed...via automated scripting. 

I set :

```
$userID = 1;  
```

And Use this Method on first Auth of my app. (I have noticed that the uid is not properly set in the DB once this insert is made, it starts at the auto_inc # vs. the uid from Dropbox).

```
$storage->set($_SESSION['dropbox_api']['access_token'], 'access_token');
```

And on Use of the script: 

```
$token = $storage->get('access_token');
print_r($token);
```

My Question Being ...  

How would I access that authorized account using the token from the database?

ideally using: 

```
$dropbox->putfile('foo', 'bar');
$foo = $dropbox->shares('bar');
```

thanks in advance! - CAM

**Comment by BenExile** [comment]
Hi Cam,

The database storage handler assumes you have a user ID either from an existing user table, or a fixed/faux ID like the example I've provided (this is useful if you need a single access token to be used for multiple users - sharing a Dropbox, effectively). See the example code below:

```
$userID = 1;
$storage = new \Dropbox\OAuth\Storage\PDO($encrypter, $userID);
$storage->connect('localhost', 'dropbox', 'username', 'password', 3306);
```

When the `$userID` is passed to the storage object, it is set up to retrieve and use the token stored in the database for that user ID. The Dropbox user ID is not important here, we don't care about it, this user ID we want stored with the access token is our internal ID.

You shouldn't need to call set() or get() methods on the storage object. Once you have the token for `$userID`, you simply pass that ID to the storage handler and the rest is done for you.

Hope this helps

**Comment by chrisamoore** [comment]
Solid, I actually have it all nailed down and thank you for your rapid response. 

```
$storage->get('access_token');
$dropbox->putFile('../test/files/test_email.txt', 'test_email2.txt');
```

via the bootstrap.php
its actually not that complex once I looked at it deeper. 

Thanks!!

**Comment by BenExile** [comment]
Glad to help :)
