### ISSUE TITLE
Decouple SDK implementation from Mysql

### ISSUE THREAD

**Issue by MKxDev** [BenExile/Dropbox#62]
I'd really like to use this SDK but it looks like I'm forced to use mysql as the only storage provider (without modifying the sdk). It'd be extremely nice to be able to choose the type of storage provider (mysql, sqlite, pg, sql server) or be able to easily drop my own. Just something to thing about.

**Comment by BenExile** [comment]
You can roll your own storage handler. Check out the ones already provided for Session, Filesystem and PDO.

Sent from my HTC

----- Reply message -----

**Comment by MKxDev** [comment]
Yep, I see it now. I jumped the gun on that one.

**Comment by BenExile** [comment]
Issue resolved - closed.
