### ISSUE TITLE
Offline Usage

### ISSUE THREAD

**Issue by cyruskafaiwu** [BenExile/Dropbox#63]
Hello,

Sorry for the lame question. For running processes like putting a file in someone's dropbox without them being on the website, is there any specified way of doing it.

I haven't seen anywhere where I can just send the access token that was added when the user first authorized the app and run operations without the user being on the website.

Thanks

**Comment by BenExile** [comment]
There's no specific example for this at the moment, you'd just need to ensure you used the access token acquired for that user when making the API call.

Example: If you know the user has ID 1 in your system, and you're storing tokens using the PDO handler, make sure the user ID passed to the storage handler is 1.

I'm very busy at the moment but will try and put an example together if this doesn't make sense.

Sent from my HTC

----- Reply message -----

**Comment by cyruskafaiwu** [comment]
It makes total sense. Thanks!

**Comment by BenExile** [comment]
No problem :)
