### ISSUE TITLE
Using API within a function.

### ISSUE THREAD

**Issue by cyruskafaiwu** [BenExile/Dropbox#69]
Hello,

Not really an issue. But I want to know how I could use the API within a php regular function.

Here's what I have:
function dog() {
        global $mysqli;
        global $project;
        global $setting;
        global $db_setting;
        $userID = $destination['dropbox_id'];
        require_once('../dropbox_bootstrap.php');
        $put = $dropbox->putFile($path.'/'.$filename, $backup_file,$backup_dir,true);
}

I do receive an error message say "error".

Here is my dropbox_bootstrap.php:
<?php
if($backup_system != "1") { die("error");}

// Register a simple autoload function
spl_autoload_register(function($class){
    $class = str_replace('\', '/', $class);
    require_once('../' . $class . '.php');
});

$encrypter = new \Dropbox\OAuth\Storage\Encrypter('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');

if(isset($userID) == FALSE) {$userID = 1;}

$callback_a = 'http://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];
$url = parse_url($callback_a);
$callback = $url['scheme'].'://'.$_SERVER['HTTP_HOST'].''.$url['path'].'?'.http_build_query($_GET).'';

$storage = new \Dropbox\OAuth\Storage\PDO($encrypter, $userID);
$storage->connect($db_setting['host'],$db_setting['name'], $db_setting['username'], $db_setting['password'], 3306);
$storage->setTable('dropbox_oauth_tokens');

$OAuth = new \Dropbox\OAuth\Consumer\Curl($setting['dropbox_key'], $setting['dropbox_secret'], $storage, $callback);
$dropbox = new \Dropbox\API($OAuth);
?>

**Comment by BenExile** [comment]
Hi @cyruskafaiwu,

The error message, "error", you're seeing does not relate to the library but this line in your bootstrap file: `if($backup_system != "1") { die("error");}`. Try ensuring `$backup_system == 1`?

Unfortunately I'm unable to support custom code, but if you still have issues with the library once this is resolved then I'm happy to help.
