### ISSUE TITLE
PDO should call parent on delete

### ISSUE THREAD

**Issue by JoniJnm** [BenExile/Dropbox#71]
Hi,

I think that in PDO::delete() you should call Session::delete().

So, it looks something like:

```
public function delete()
{
    $ok = parent::delete();
    return execSQL("DELETE FROM premium_oauth_user_tokens WHERE IDUSUARIO='".formatearParaDB($this->userID)."' AND APP='dropbox'") > 0 && $ok;
}
```

**Comment by BenExile** [comment]
Hi @JoniJnm,

It does - Please see [here](https://github.com/BenTheDesigner/Dropbox/blob/master/Dropbox/OAuth/Storage/PDO.php#L152-L168) and ensure you have pulled the latest changes, though this was added a while ago.

**Comment by JoniJnm** [comment]
Oh, sorry! It's ok ^_^

I had other version
