### ISSUE TITLE
Odd Question: what if user removes application

### ISSUE THREAD

**Issue by cyruskafaiwu** [BenExile/Dropbox#72]
If the user, removes the application from dropbox.

Is there any way we can figure out if they did so or not?

**Comment by BenExile** [comment]
The API will return an error with status code 401. I am working on better error handling, but for now you can try/catch your API calls and delete tokens if a 401 is returned.

**Comment by BenExile** [comment]
Also, if you comment on a related issue, please give me a chance to respond and don't create a new one ~10 minutes later.

**Comment by BenExile** [comment]
Closed due to inactivity
