### ISSUE TITLE
The cURL OAuth consumer requires the cURL extension

### ISSUE THREAD

**Issue by chrisrollins65** [BenExile/Dropbox#76]
I'm using wamp with php 5.4.3. I've activated curl and checked phpinfo and the error log to make sure it's enabled. I'm trying to test this out, setting it up through cmd on Windows 7 x64, but I'm getting a bunch of undefined constant errors as pasted below. Any idea what's going on? I appreciate the help!

PHP Notice:  Use of undefined constant CURLOPT_SSL_VERIFYPEER - assumed 'CURLOPT
_SSL_VERIFYPEER' in C:\wamp\www\jlocalhost\Dropbox-master\tests\setup.php on lin
e 46
PHP Stack trace:
PHP   1. {main}() C:\wamp\www\jlocalhost\Dropbox-master\tests\setup.php:0

Notice: Use of undefined constant CURLOPT_SSL_VERIFYPEER - assumed 'CURLOPT_SSL_
VERIFYPEER' in C:\wamp\www\jlocalhost\Dropbox-master\tests\setup.php on line 46

Call Stack:
    0.0047     241432   1. {main}() C:\wamp\www\jlocalhost\Dropbox-master\tests\
setup.php:0

PHP Notice:  Use of undefined constant CURLOPT_VERBOSE - assumed 'CURLOPT_VERBOS
E' in C:\wamp\www\jlocalhost\Dropbox-master\tests\setup.php on line 46
PHP Stack trace:
PHP   1. {main}() C:\wamp\www\jlocalhost\Dropbox-master\tests\setup.php:0

Notice: Use of undefined constant CURLOPT_VERBOSE - assumed 'CURLOPT_VERBOSE' in
 C:\wamp\www\jlocalhost\Dropbox-master\tests\setup.php on line 46

Call Stack:
    0.0047     241432   1. {main}() C:\wamp\www\jlocalhost\Dropbox-master\tests\
setup.php:0

PHP Notice:  Use of undefined constant CURLOPT_HEADER - assumed 'CURLOPT_HEADER'
 in C:\wamp\www\jlocalhost\Dropbox-master\tests\setup.php on line 46
PHP Stack trace:
PHP   1. {main}() C:\wamp\www\jlocalhost\Dropbox-master\tests\setup.php:0

Notice: Use of undefined constant CURLOPT_HEADER - assumed 'CURLOPT_HEADER' in C
:\wamp\www\jlocalhost\Dropbox-master\tests\setup.php on line 46

Call Stack:
    0.0047     241432   1. {main}() C:\wamp\www\jlocalhost\Dropbox-master\tests\
setup.php:0

PHP Notice:  Use of undefined constant CURLINFO_HEADER_OUT - assumed 'CURLINFO_H
EADER_OUT' in C:\wamp\www\jlocalhost\Dropbox-master\tests\setup.php on line 46
PHP Stack trace:
PHP   1. {main}() C:\wamp\www\jlocalhost\Dropbox-master\tests\setup.php:0

Notice: Use of undefined constant CURLINFO_HEADER_OUT - assumed 'CURLINFO_HEADER
_OUT' in C:\wamp\www\jlocalhost\Dropbox-master\tests\setup.php on line 46

Call Stack:
    0.0047     241432   1. {main}() C:\wamp\www\jlocalhost\Dropbox-master\tests\
setup.php:0

PHP Notice:  Use of undefined constant CURLOPT_RETURNTRANSFER - assumed 'CURLOPT
_RETURNTRANSFER' in C:\wamp\www\jlocalhost\Dropbox-master\tests\setup.php on lin
e 46
PHP Stack trace:
PHP   1. {main}() C:\wamp\www\jlocalhost\Dropbox-master\tests\setup.php:0

Notice: Use of undefined constant CURLOPT_RETURNTRANSFER - assumed 'CURLOPT_RETU
RNTRANSFER' in C:\wamp\www\jlocalhost\Dropbox-master\tests\setup.php on line 46

Call Stack:
    0.0047     241432   1. {main}() C:\wamp\www\jlocalhost\Dropbox-master\tests\
setup.php:0

PHP Notice:  Use of undefined constant CURLOPT_FOLLOWLOCATION - assumed 'CURLOPT
_FOLLOWLOCATION' in C:\wamp\www\jlocalhost\Dropbox-master\tests\setup.php on lin
e 46
PHP Stack trace:
PHP   1. {main}() C:\wamp\www\jlocalhost\Dropbox-master\tests\setup.php:0

Notice: Use of undefined constant CURLOPT_FOLLOWLOCATION - assumed 'CURLOPT_FOLL
OWLOCATION' in C:\wamp\www\jlocalhost\Dropbox-master\tests\setup.php on line 46

Call Stack:
    0.0047     241432   1. {main}() C:\wamp\www\jlocalhost\Dropbox-master\tests\
setup.php:0

The cURL OAuth consumer requires the cURL extension
Setup failed! Please try running setup again.

**Comment by BenExile** [comment]
Hi @epsilon1983 

This definitely suggests that cURL is not enabled. Can you confirm that you only have one PHP install on your machine? Could it be possible that PHP in your PATH is a different version? Can you also confirm that you have checked that cURL is enabled via CLI? (`php -i > phpinfo.txt` or similar and check the output does specify that cURL support is enabled).

**Comment by chrisrollins65** [comment]
Hmm, I did as you said and curl was in fact not shown as enabled. In the wamp settings and phpinfo() it showed enabled. So I went into php.ini manually (I could've swore I checked it before, but oh well), and it was still commented out. I uncommented it and now it's working. Thanks for all the help!
