### ISSUE TITLE
Problem with putStream

### ISSUE THREAD

**Issue by krajcsovszkig** [BenExile/Dropbox#77]
Hi!

I love your API, but I've come across a problem with putStream: putFile works fine, but putStream throws this:

Parameter not found: oauth_consumer_key

File D:\programs\binaries\xampp\htdocs\Krajcsovszki.Gergely\resources\engine\Dropbox\OAuth\Consumer\Curl.php, line 153

Trace:
#0 D:\programs\binaries\xampp\htdocs\Krajcsovszki.Gergely\resources\engine\Dropbox\API.php(495): Dropbox\OAuth\Consumer\Curl->fetch('PUT', 'https://api-con', 'files_put/sandb...', Array)
#1 D:\programs\binaries\xampp\htdocs\Krajcsovszki.Gergely\resources\engine\Dropbox\API.php(135): Dropbox\API->fetch('PUT', 'https://api-con', 'files_put/sandb...', Array)
#2 D:\programs\binaries\xampp\htdocs\Krajcsovszki.Gergely\content\hu\actions\components\post_homework\script_uploader.php(88): Dropbox\API->putStream(Resource id #28, 'test/Teszt h??z...')
#3 D:\programs\binaries\xampp\htdocs\Krajcsovszki.Gergely\content\hu\actions\post_homework.php(93): processUpload()
#4 {main}

I've var_dumped the $request that generates in Curl.php line 76 and it contains the oauth_consumer_key the same way both for putFile and putStream, so it's really weird.

It did work with your Session storage handler, but when I switched to mine that reads the token from a file (code [here](http://pastebin.com/Jn8zSZkF)) it becomes like this.

I use it like this:

```
$storage = new \Dropbox\OAuth\Storage\SimpleFile($encrypter, $tokenDir, 'dropbox', false, false);
```

What could be the problem? I would just stick with putFile, but my webmaster doesn't allow creating files with php for "security reasons", so I can only open temp streams and push them.

Thanks.

**Comment by krajcsovszkig** [comment]
Update:

I tried again with the Session storage handler and now that didn't work either.

I also tried looking after the problem and I read somewhere that you should always use HMAC-SHA1 signature method, but if I try $OAuth->setSignatureMethod('HMAC-SHA1'); I get an "Invalid or missing signature" error for every request.

**Comment by krajcsovszkig** [comment]
I fixed it, it turned out I messed it up:

I read data, like the consumer key from an xml like this:

```
$key = $configFile->xpath("/dropboxConfigs/appKey"); $key = $key[0];
```

This way, the $key will be a simplexmlelement, and this way, for some reason, the consumer key gets into the url like this:

```
oauth_consumer_key%5B0%5D=<key>
```

Now I changed it like this:

```
$key = $configFile->xpath("/dropboxConfigs/appKey"); $key = (string)$key[0];
```

and it works.

It's weird though that it didn't cause an issue with putFile, only with the other methods.

**Comment by BenExile** [comment]
Hi @krajcsovszkig 

Sorry for the delayed response on this. Been busy. Glad you got it sorted.
