### ISSUE TITLE
Warning: Unexpected character in input: '\' (ASCII=92) state=1

### ISSUE THREAD

**Issue by markfilops** [BenExile/Dropbox#78]
Hey there,

I know I'm missing something blindingly obvious, but when I try to run almost any of the example scripts I get the following:

```
Warning: Unexpected character in input: '\' (ASCII=92) state=1 in [snip]/includes/dropbox/examples/accountInfo.php on line 15

Warning: Unexpected character in input: '\' (ASCII=92) state=1 in [snip]/includes/dropbox/examples/accountInfo.php on line 15

Parse error: syntax error, unexpected T_STRING, expecting T_VARIABLE in [snip]/includes/dropbox/examples/accountInfo.php on line 15
```

This is when I try and run accountInfo.php

Any hints?

**Comment by BenExile** [comment]
Hi @markfilops 

Looks like you're not running PHP 5.3 or above. Correct? As described in the readme, this library requires PHP 5.3.1 or higher.

**Comment by markfilops** [comment]
Absolutely correct. And a hosting service that refuses to upgrade resellers to recent versions of PHP. New hosting service, now all is good.

Thanks for your time.
