### ISSUE TITLE
Can ConsumerAbstract->getRequestToken be public?

### ISSUE THREAD

**Issue by sfreytag** [BenExile/Dropbox#79]
ConsumerAbstract->getAccessToken is public.

Would it be possible to make ->getRequestToken public also? (currently it is private)

I'm using your excellent API in a project, but I don't want instant authentication when I instantiate my Curl object. 

One solution would be to write my own implementation of ConsumerAbstract, but this feels like overkill because your Curl implementation is absolutely fine! 

So I have overridden Curl, very simply, such that the constructor doesn't call authenticate(). Instead I call it when I am ready, by checking if the user is authenticated, if not generating the URL, giving the user a 'auth now' button, and then finally calling authorise(). Hence I want to call getRequestToken to generate an authorisation URL which I can return to my user interface, to display the nice 'authorise now' button.

Obviously I have worked around this for now by hacking ConsumerAbstract, but it'd be great if this change is acceptable to you for it to be merged into your repo, then I can continue to work with a vanilla checkout, instead of a hacked one, and thus make my future upgrades much easier!

I'll submit a pull request shortly.

Thanks,

Simon

**Comment by BenExile** [comment]
Hi @sfreytag 

Pull request merged a minute ago. Thanks for your contribution!
