### ISSUE TITLE
"This app has been disabled."

### ISSUE THREAD

**Issue by GerardUmbert** [BenExile/Dropbox#86]
I keep getting this error. "This app has been disabled." (curl.php 153)
I might be retard but... what else am I supposed to do apart from giving correct values to bootstrap.php?

**Comment by BenExile** [comment]
Hi,

That sounds like an error being returned by Dropbox. Not seen it myself, but I'd say make sure you're passing the correct value for dropbox/sandbox mode and log into  https://www.dropbox.com/developers and check your key/secret. If you still have issues submit a rocket to Dropbox and see if they can shed any light on the problem.

**Comment by GerardUmbert** [comment]
Somehow I messed up the key value, its definetly 100% different from the one I entered, this is kinda weird since I copy-pasted it directly from the console... but... ok.

Works now, thanks, and sorry for bothering.

**Comment by BenExile** [comment]
No problem :) Resolved.
