### ISSUE TITLE
Errors in ConsumerAbstract.php file

### ISSUE THREAD

**Issue by johnmullin2003** [BenExile/Dropbox#9]
Hello,

I've got  those errors in my webserver:

_Notice: Undefined offset: 1 in ....../Dropbox/OAuth/Consumer/ConsumerAbstract.php on line 281
Fatal error: Cannot access empty property in ....../Dropbox/OAuth/Consumer/ConsumerAbstract.php on line 283_

my hosted webserver has PHP Version 5.3.2 with cURL and mCrypt support.

Thanks for your help,

jM

**Comment by johnmullin2003** [comment]
I googled a bit and I think I solved this error changin into:
_$token->k = $v;_

Thanks again

**Comment by BenExile** [comment]
Hi @johnmullin2003 

Your environment sounds fine. That notice suggests that the response from Dropbox was malformed in some way - it was unable to split the response and set the properties of the token object. This could have been caused by many things (Dropbox platform availability, connectivity issues etc) and I'd really need to see the original response to debug. Are you able to replicate?

Please note that `$token->$k` ([variable variable](http://php.net/manual/en/language.variables.variable.php)) does not behave the same as `$token->k` and you may experience unexpected results.

**Comment by johnmullin2003** [comment]
@BenTheDesigner , thanks for your fast answer.
Infact I ran php files in 2 different webservers.  
In he first one (php 5.3.10), everything is ok without any edit.
In the second one, (php 5.3.2) it gave me the error. You were right when you typed that I may experience unexpected results, infact that error message isn't shown now, but I get the message: "The request to link the app is invalid." after loggin in the Dropbox home page...

Any idea about how to fix the problem? I'm not so OO. PHP skilled! :-)

Thanks for helping

**Comment by BenExile** [comment]
Hi @johnmullin2003 

This issue is not apparent in my install of 5.3.2. To help you debug I will need to see the requests/responses. It will be easier if you call `$OAuth->setSignatureMethod('PLAINTEXT')` and replace your sensitive details with XXX (or similar).

How long after being redirected to Dropbox did you authorise the application? The message you're receiving could be related to an expired request token, but that is a wild guess.

**Comment by johnmullin2003** [comment]
Hi @BenTheDesigner , thanks again for you help.

The webserver that gives me those problems is the [my school project](http://pwdwallet.sourceforge.net/info.php) @ sourceforge.net.

There, I edit my 'getFile.php' placing the call `$OAuth->setSignatureMethod('PLAINTEXT')` after the `require_once('bootstrap.php')` line, but nothing happened because the error gets out in [dropbox page](http://i40.tinypic.com/14vjms4.png) after loggin-in (and authorising app).
I think I've to re-edit ConsumerAbstract.php file in its original way..but the server will print out the first error in this discussion...

How (and what I have to do) can I debug and see reqs/responses?

I authorised my app after landing on dropbox page.
Thank you very much for support

**Comment by BenExile** [comment]
Hi @johnmullin2003 

To ensure all requests are signed using PLAINTEXT I'd advise setting it just after the `$OAuth` object is created (in bootstrap.php) and before it is passed to `$dropbox`.

Debugging OAuth related issues is a PITA - the easiest way I can think of would be to edit \Dropbox\OAuth\Consumer\Curl (see fetch() method), and `var_dump($request)` just after the call to `$this->getSignedRequest()`. Once you've done this you can compare what _should_ be identical requests across systems and check for inconsistencies. I hope this helps, and please post your results.

**Comment by johnmullin2003** [comment]
Hi @BenTheDesigner , I followed your instructions and I get this response:

> array(2) { ["url"]=> string(252) "https://api.dropbox.com/1/oauth/request_token?oauth_consumer_key=MYCONSKEY&oauth_nonce=3ccc4f590138c393fdfdae141dc6e4ef&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1330514635&oauth_version=1.0&oauth_signature=1ZcG46e7%2FQhBNXHAt4csZbyzIR8%3D" ["postfields"]=> array(6) { ["oauth_consumer_key"]=> string(15) "MYCONSKEY" ["oauth_nonce"]=> string(32) "3ccc4f590138c393fdfdae141dc6e4ef" ["oauth_signature_method"]=> string(9) "HMAC-SHA1" ["oauth_timestamp"]=> int(1330514635) ["oauth_version"]=> string(3) "1.0" ["oauth_signature"]=> string(28) "1ZcG46e7/QhBNXHAt4csZbyzIR8=" } } 
> 
> Notice: Undefined offset: 1 in /home/project-web/MYPROJECT/htdocs/Dropbox/OAuth/Consumer/ConsumerAbstract.php on line 281
> 
> Fatal error: Cannot access empty property in /home/project-web/MYPROJECT/htdocs/Dropbox/OAuth/Consumer/ConsumerAbstract.php on line 283

Please note that i _didnt'_ edit ConsumerAbstract.php ( there is: `$token->$k = $v` ).
My consumer app key in the request response is the same.

Thanks for your support.

**Comment by BenExile** [comment]
Hi @johnmullin2003 

Can you `var_dump($response)` inside ConsumerAbstract::parseTokenString() and paste the output? This will enable me to see if the value passed is malformed. I'm still unable to replicate in any version of PHP.

**Comment by johnmullin2003** [comment]
Hi @BenTheDesigner ,  this is the output:

> array(2) { ["url"]=> string(252) "https://api.dropbox.com/1/oauth/request_token?oauth_consumer_key=MYCONSKEY&oauth_nonce=74bbd0c67d14e4b5838ed91a8edb3638&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1330547903&oauth_version=1.0&oauth_signature=BN9RGAegVJvgY%2BbR17HrkZF8pzM%3D" ["postfields"]=> array(6) { ["oauth_consumer_key"]=> string(15) "MYCONSKEY" ["oauth_nonce"]=> string(32) "74bbd0c67d14e4b5838ed91a8edb3638" ["oauth_signature_method"]=> string(9) "HMAC-SHA1" ["oauth_timestamp"]=> int(1330547903) ["oauth_version"]=> string(3) "1.0" ["oauth_signature"]=> string(28) "BN9RGAegVJvgY+bR17HrkZF8pzM=" } } 
> 
> parseTokenString() response:
> NULL 
> 
> Notice: Undefined offset: 1 in /home/project-web/MYPROJECT/htdocs/Dropbox/OAuth/Consumer/ConsumerAbstract.php on line 281
> 
> Fatal error: Cannot access empty property in /home/project-web/MYPROJECT/htdocs/Dropbox/OAuth/Consumer/ConsumerAbstract.php on line 283

I'm trying to host the files on [SourceForge project web workspace](http://sourceforge.net/apps/trac/sourceforge/wiki/Project%20web) because this is the highly suggested place for my school project... 
If it can't be possibile, I'll host my web project in another location.

Thanks again

**Comment by BenExile** [comment]
Hi @johnmullin2003 

Unfortunately the support I can offer is limited as I'm unable to replicate this issue on any platform.

What I'm after is the raw HTTP response from the API server - see `\Dropbox\OAuth\Consumer\Curl::fetch()`. In your last comment you said the response was null, but cURL returns false on failure, not null. Please ensure you dump `$response` after `curl_exec()` is called.

I'm not sure this is a bug with the library but will help where I can. You will, however, need to spend some time debugging at your end.
