### ISSUE TITLE
Apps/TestFolder rights question

### ISSUE THREAD

**Issue by kemppaij** [BenExile/Dropbox#91]
Hi!
Nice code, I got it working. I would still though have a question. I've created an App with my dropbox account. Now I've managed to authenticate three different users. They all authenticated and are able to see this created Apps/TestFolder. When I upload something there or somebody else, I can only see my own uploads and the others their own? Is this normal behaviour or isn't it possible to share this folder, so when I upload a file there, the others are able to see it? With their existing dropbox client (web/phone/desktop)?

**Comment by BenExile** [comment]
Just to confirm, the app folder that is created if the application root is "sandbox" is not shared between authenticated users.
