### ISSUE TITLE
How to use this library without Composer?

### ISSUE THREAD

**Issue by PaulJBis** [BenExile/Dropbox#97]
Hello:

I am trying to use your library in a simple PHP app that will be running on a shared host. Since my shared host doesn't have Composer nor shell access, I'm trying to figure out how to include your library in my app without having to install Composer. I tried moving the `Dropbox/` folder to the same folder where I have my script; then I moved the `bootstrap.php` to that same folder, and edited it in this way:

```
spl_autoload_register(function($class){
    $class = str_replace('\\', '/', $class);
    require_once('./Dropbox/' . $class . '.php');
});
```

And then I included `bootstrap.php` in the first line of my script... but it didn't work:

```
Fatal error: require_once(): Failed opening required './Dropbox/Dropbox/OAuth/Storage/Encrypter.php' (include_path='.:/usr/local/php5.4/lib/php') in /home/caminofaky/www/backup/bootstrap.php on line 26
```

How can I do this? Thanks.

**Comment by eusonlito** [comment]
And

``` php
spl_autoload_register(function($class) {
    require __DIR__.'/'.str_replace('\\', '/', $class).'.php';
});
```

?

**Comment by PaulJBis** [comment]
Thanks!
